name = "buscore-lighthouse"
main = "src/index.ts"
compatibility_date = "2026-02-26"

[vars]
MANIFEST_URL = "https://buscore.ca/manifest/core/stable.json"

[[d1_databases]]
binding = "DB"
database_name = "buscore-lighthouse"
database_id = "7d71a1a1-fb48-4050-8cf3-b489e607d20e"

[triggers]
crons = ["0 9 * * *"]
